# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-trollbridge

# >> macros
# << macros

Summary:    TRaveller's OLympus Bridge
Version:    0.2.0
Release:    1
Group:      Applications/Multimedia
License:    MIT
BuildArch:  noarch
Source0:    %{name}-%{version}.tar.gz
Source100:  harbour-trollbridge.yaml
Source101:  harbour-trollbridge-rpmlintrc
Requires:   libsailfishapp-launcher
Requires:   python3-base
Requires:   python3dist(pycurl)
Requires:   python3dist(olympuswifi)
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  sailfish-svg2png
BuildRequires:  qml-rpm-macros
BuildRequires:  desktop-file-utils

%description
TRaveller's OLympus Bridge is an app for controlling Olympus OM-D/PEN/Air cameras with integrated WiFi.

%if "%{?vendor}" == "chum"
PackageName: Troll Bridge
Type: desktop-application
DeveloperName: Bundyo, nephros
DeveloperLogin: nephros
PackagerName: nephros
Categories:
 - Media
Custom:
  Repo: %{url}
Icon: %{url}/master/icons/svgs/%{name}.svg
Url:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
  Donations: https://openrepos.net/donate
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/applications/*.desktop
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/qml/*
%{_datadir}/%{name}/py/*
%{_datadir}/%{name}/translations/%{name}-*.qm
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/icons/hicolor/*/apps/%{name}.svg
# >> files
# << files
